[[flashrom]]
arch = "aarch64"
git-tree-sha1 = "5dc76e563d93641367555ff5596aa9805fcc86c7"
libc = "glibc"
os = "linux"

    [[flashrom.download]]
    sha256 = "019dbaacc5b1142db0b9e4d2084626e571ffa20b53673422b7c22c867dca8311"
    url = "https://github.com/JuliaBinaryWrappers/flashrom_jll.jl/releases/download/flashrom-v1.2.900+1/flashrom.v1.2.900.aarch64-linux-gnu.tar.gz"
[[flashrom]]
arch = "aarch64"
git-tree-sha1 = "cd9c8b31918cb40707b9530aff19e35f02478e50"
libc = "musl"
os = "linux"

    [[flashrom.download]]
    sha256 = "3cbb8a8fe4d35ca69f5a79b8caa112b3b9ffc274dcc9597bfecf9845e1743a4a"
    url = "https://github.com/JuliaBinaryWrappers/flashrom_jll.jl/releases/download/flashrom-v1.2.900+1/flashrom.v1.2.900.aarch64-linux-musl.tar.gz"
[[flashrom]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "50f3baf6d74933cf86a6048bc5417df66d76496a"
libc = "glibc"
os = "linux"

    [[flashrom.download]]
    sha256 = "398367c33d0119a1e763b89f9e5926c86bccf5172c6bbc6eeedce50ef1ad1a7c"
    url = "https://github.com/JuliaBinaryWrappers/flashrom_jll.jl/releases/download/flashrom-v1.2.900+1/flashrom.v1.2.900.armv6l-linux-gnueabihf.tar.gz"
[[flashrom]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bcbc1cd0856d6893bf28350e64d63a24bdc47abf"
libc = "musl"
os = "linux"

    [[flashrom.download]]
    sha256 = "753b7416a9e63b942047dbafe53478adf1de61d2be50bc17693bf8374943b88c"
    url = "https://github.com/JuliaBinaryWrappers/flashrom_jll.jl/releases/download/flashrom-v1.2.900+1/flashrom.v1.2.900.armv6l-linux-musleabihf.tar.gz"
[[flashrom]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3393656cd28477e74936932f3bf7818ab5e3518b"
libc = "glibc"
os = "linux"

    [[flashrom.download]]
    sha256 = "fc310e6e4372d724855618e5794cb9cba498cc961f11916c5467037fac396905"
    url = "https://github.com/JuliaBinaryWrappers/flashrom_jll.jl/releases/download/flashrom-v1.2.900+1/flashrom.v1.2.900.armv7l-linux-gnueabihf.tar.gz"
[[flashrom]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "68a93b30d31f375194d5e3b143a769265e3d6910"
libc = "musl"
os = "linux"

    [[flashrom.download]]
    sha256 = "d8024baadad89f7023484817a6a0da1bf868db0ef2cddcd283ea49b0c0086249"
    url = "https://github.com/JuliaBinaryWrappers/flashrom_jll.jl/releases/download/flashrom-v1.2.900+1/flashrom.v1.2.900.armv7l-linux-musleabihf.tar.gz"
[[flashrom]]
arch = "i686"
git-tree-sha1 = "46710d5faebec5dd1cb0df9c28d2d2e2aefbe09f"
libc = "glibc"
os = "linux"

    [[flashrom.download]]
    sha256 = "341b7797dc1727b6c88b650b714888d588e6dccdfa638afe1f178e6ab64845b4"
    url = "https://github.com/JuliaBinaryWrappers/flashrom_jll.jl/releases/download/flashrom-v1.2.900+1/flashrom.v1.2.900.i686-linux-gnu.tar.gz"
[[flashrom]]
arch = "i686"
git-tree-sha1 = "4497cfba33181ceb6395e775b28a295926931b46"
libc = "musl"
os = "linux"

    [[flashrom.download]]
    sha256 = "b173796c120b08a3421adb75ac7266fd8dabc67d0b6fcd351e7727ca4e616174"
    url = "https://github.com/JuliaBinaryWrappers/flashrom_jll.jl/releases/download/flashrom-v1.2.900+1/flashrom.v1.2.900.i686-linux-musl.tar.gz"
[[flashrom]]
arch = "x86_64"
git-tree-sha1 = "cc0f779b5b8fdef31bf541a4951373ec30cfa1f9"
libc = "glibc"
os = "linux"

    [[flashrom.download]]
    sha256 = "10d1d4e3d2ae8ca47d06f3e0ded01eed6bf06e34bdbdcb5888a03e34103ca324"
    url = "https://github.com/JuliaBinaryWrappers/flashrom_jll.jl/releases/download/flashrom-v1.2.900+1/flashrom.v1.2.900.x86_64-linux-gnu.tar.gz"
[[flashrom]]
arch = "x86_64"
git-tree-sha1 = "e3fd2760546c3637ab5cbbcee0d16a49e899de62"
libc = "musl"
os = "linux"

    [[flashrom.download]]
    sha256 = "5073e694c91a58bfa300ef2157b4068d1acd73c34356d074c47ddd68f9f9de11"
    url = "https://github.com/JuliaBinaryWrappers/flashrom_jll.jl/releases/download/flashrom-v1.2.900+1/flashrom.v1.2.900.x86_64-linux-musl.tar.gz"
